- name: Deploy Mysql Database
  hosts:  guacamole
  tasks:
    - name: Install pip with python3
      apt: update_cache=yes name=python3-pip state=latest

    - name: Install Docker compose Module
      pip:
        name: docker-compose

    - name: Copia o arquivo do docker-compose
      copy: 
        src: ../docker/docker-compose.yml
        dest: /tmp/docker-compose.yml

    - name: Deploy mysql datadase
      docker_compose:
        project_src: /tmp
        files: docker-compose.yml