- name: Deploy GUACD container
  hosts:  guacamole
  tasks:
    - name: Create GUACD
      docker_container:
        name: guacd
        image: guacamole/guacd
        ports:
          - "4822:4822"
        links:
          - bdMysql:bdMysql
        networks:
          - name: "tmp_guacamole-net"
            ipv4_address: 172.19.0.3