- name: Deploy GUACD container
  hosts:  guacamole
  tasks:
    - name: Create GUACD
      docker_container:
        name: guacd
        image: guacamole/guacd
        exposed_ports:
          - 4822
        links:
          - bdMysql:bdMysql
        networks:
          - name: "tmp_guacamole-net"